// kb-data.mjs -- pull the live equipment catalog out of Supabase and print it
// as compact, chatbot-ready markdown (one line per machine, grouped by category).
//
// The website reads products from Supabase at runtime (useProducts.js), so a
// repo-only scan never sees them -- this script is the KB pipeline's data step.
// Prices are printed GROSS (x1.23), matching what the site shows to visitors.
//
// Usage: node scripts/kb-data.mjs            (markdown to stdout)
//        node scripts/kb-data.mjs --json     (raw rows as JSON)

import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

// Minimal .env reader -- same vars Vite injects for the site client.
function loadEnv() {
  const env = { ...process.env };
  try {
    for (const line of readFileSync(resolve(root, '.env'), 'utf8').split('\n')) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*"?([^"\r\n]*)"?\s*$/);
      if (m && !(m[1] in env)) env[m[1]] = m[2];
    }
  } catch { /* .env optional if vars come from the environment */ }
  return env;
}

const env = loadEnv();
const SUPABASE_URL = env.VITE_SUPABASE_URL;
const SUPABASE_KEY = env.VITE_SUPABASE_ANON_KEY;
if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('Missing VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY (.env or environment).');
  process.exit(1);
}

const res = await fetch(
  `${SUPABASE_URL}/rest/v1/equipment?select=name,slug,daily_rate_base,pricing_type,in_stock,is_popular,equipment_categories(name,slug),equipment_subcategories(name,slug)&status=eq.active&order=name`,
  { headers: { apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}` } },
);
if (!res.ok) {
  console.error(`Supabase fetch failed: ${res.status} ${res.statusText}`);
  process.exit(1);
}
const rows = await res.json();

if (process.argv.includes('--json')) {
  console.log(JSON.stringify(rows, null, 2));
  process.exit(0);
}

const grossPrice = (r) => {
  if (r.pricing_type === 'negotiable' || !r.daily_rate_base) return 'cena na požiadanie';
  return `${(Math.round(r.daily_rate_base * 1.23 * 100) / 100).toString().replace('.', ',')} €/deň s DPH`;
};

// Group by category, keep site ordering inside (already ordered by name).
const byCat = new Map();
for (const r of rows) {
  const cat = r.equipment_categories?.name || 'Ostatné';
  if (!byCat.has(cat)) byCat.set(cat, []);
  byCat.get(cat).push(r);
}

const today = new Date().toISOString().slice(0, 10);
const out = [];
out.push(`<!-- Generated by scripts/kb-data.mjs on ${today} from Supabase (status=active). Do not edit by hand -- rerun the script. -->`);
out.push('');
for (const [cat, items] of byCat) {
  out.push(`## ${cat} (${items.length})`);
  out.push('');
  for (const r of items) {
    const sub = r.equipment_subcategories?.name;
    const bits = [grossPrice(r)];
    if (sub) bits.push(sub.toLowerCase());
    if (r.in_stock === false) bits.push('momentálne nedostupné');
    out.push(`- **${r.name}** — ${bits.join(' · ')} — https://royalstroje.sk/pozicovna/${r.slug}`);
  }
  out.push('');
}
out.push(`Spolu ${rows.length} strojov v ponuke. Kompletný katalóg: https://royalstroje.sk/katalog`);
console.log(out.join('\n'));
