// kb-data.mjs -- pull the live equipment catalog out of Supabase and print it
// as compact, chatbot-ready markdown (one line per machine, grouped by category).
//
// The website reads products from Supabase at runtime (useProducts.js), so a
// repo-only scan never sees them -- this script is the KB pipeline's data step.
//
// Three things here are load-bearing and were all wrong in the first version
// (fixed 2026-08-25 after watching the live bot answer):
//   1. Prices are printed NET (daily_rate_base as-is, "bez DPH") because that
//      is the number the catalog cards and product pages show first.
//   2. Product URLs are https://royalstroje.sk/<slug> -- the detail route is
//      the catch-all "/:productId", there is NO /pozicovna/ segment.
//   3. Every machine carries BOTH names: equipment.description is the human
//      title on the card ("Stavebny vysavac 20L") and equipment.name is the
//      model ("Bosch AdvancedVac 20"). Emitting only the model made the bot
//      deny products a visitor asked for by their catalog title.
// Products are grouped by subcategory and each group heading carries its
// catalog-filter URL, so the bot can offer the right subcategory listing when
// it cannot match one exact machine.
//
// Usage: node scripts/kb-data.mjs            (markdown to stdout)
//        node scripts/kb-data.mjs --json     (raw rows as JSON)

import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

// Minimal .env reader -- same vars Vite injects for the site client.
function loadEnv() {
  const env = { ...process.env };
  try {
    for (const line of readFileSync(resolve(root, '.env'), 'utf8').split('\n')) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*"?([^"\r\n]*)"?\s*$/);
      if (m && !(m[1] in env)) env[m[1]] = m[2];
    }
  } catch { /* .env optional if vars come from the environment */ }
  return env;
}

const env = loadEnv();
const SUPABASE_URL = env.VITE_SUPABASE_URL;
const SUPABASE_KEY = env.VITE_SUPABASE_ANON_KEY;
if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('Missing VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY (.env or environment).');
  process.exit(1);
}

const res = await fetch(
  `${SUPABASE_URL}/rest/v1/equipment?select=name,description,slug,daily_rate_base,pricing_type,in_stock,is_popular,equipment_categories(name,slug),equipment_subcategories(name,slug)&status=eq.active&order=name`,
  { headers: { apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}` } },
);
if (!res.ok) {
  console.error(`Supabase fetch failed: ${res.status} ${res.statusText}`);
  process.exit(1);
}
const rows = await res.json();

if (process.argv.includes('--json')) {
  console.log(JSON.stringify(rows, null, 2));
  process.exit(0);
}

// NET price -- what the visitor sees first on every card and detail page.
const netPrice = (r) => {
  if (r.pricing_type === 'negotiable' || !r.daily_rate_base) return 'cena na požiadanie';
  return `${r.daily_rate_base.toFixed(2).replace('.', ',')} €/deň bez DPH`;
};

// Catalog filter URL for one subcategory. The catalog lives on the homepage and
// reads ?category=&subcategory= from the query string (Catalog.jsx).
const subcategoryUrl = (catSlug, subSlug) =>
  `https://royalstroje.sk/?category=${catSlug}&subcategory=${subSlug}#katalog`;

// Group by category, then by subcategory inside it (rows already ordered by name).
const byCat = new Map();
for (const r of rows) {
  const catName = r.equipment_categories?.name || 'Ostatné';
  if (!byCat.has(catName)) {
    byCat.set(catName, { slug: r.equipment_categories?.slug || '', subs: new Map(), count: 0 });
  }
  const cat = byCat.get(catName);
  const subName = r.equipment_subcategories?.name || 'Ostatné';
  if (!cat.subs.has(subName)) {
    cat.subs.set(subName, { slug: r.equipment_subcategories?.slug || '', items: [] });
  }
  cat.subs.get(subName).items.push(r);
  cat.count += 1;
}

const today = new Date().toISOString().slice(0, 10);
const out = [];
out.push(`<!-- Generated by scripts/kb-data.mjs on ${today} from Supabase (status=active). Do not edit by hand -- rerun the script. -->`);
out.push('');
for (const [catName, cat] of byCat) {
  out.push(`## ${catName} (${cat.count})`);
  out.push('');
  for (const [subName, sub] of cat.subs) {
    const heading = cat.slug && sub.slug
      ? `### ${subName} (${sub.items.length}) — zoznam v katalógu: ${subcategoryUrl(cat.slug, sub.slug)}`
      : `### ${subName} (${sub.items.length})`;
    out.push(heading);
    out.push('');
    for (const r of sub.items) {
      // The card title (description) is how visitors name a machine; the model
      // (name) is how the paperwork names it. The bot needs to match both.
      const title = r.description && r.description !== r.name ? r.description : r.name;
      const model = title === r.name ? '' : ` (${r.name})`;
      const bits = [netPrice(r)];
      if (r.in_stock === false) bits.push('momentálne nedostupné');
      out.push(`- **${title}**${model} — ${bits.join(' · ')} — https://royalstroje.sk/${r.slug}`);
    }
    out.push('');
  }
}
out.push(`Spolu ${rows.length} strojov v ponuke. Kompletný katalóg: https://royalstroje.sk/katalog`);
console.log(out.join('\n'));
